name: Lint

on:
  push:
    branches: [main]
    paths-ignore:
      - 'example/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'example/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run linter
        run: uv run ruff check --fix

      - name: Run formatter
        run: uv run ruff format
